# Generated by Django 5.2.1 on 2025-05-19 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('category', models.CharField(choices=[('NUTRITION', 'Спортпит'), ('EQUIPMENT', 'Снаряжение'), ('CLOTHING', 'Одежда'), ('ACCESSORY', 'Аксессуары')], max_length=20)),
                ('description', models.TextField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('image_url', models.URLField()),
                ('store_links', models.JSONField()),
                ('sport_types', models.CharField(max_length=100)),
                ('keywords', models.CharField(max_length=200)),
                ('target_gender', models.CharField(choices=[('M', 'Мужской'), ('F', 'Женский')], default='M', max_length=1)),
                ('popularity_score', models.FloatField(default=0.0)),
            ],
        ),
    ]
