# Generated by Django 5.2.1 on 2025-05-19 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Training',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('category', models.CharField(max_length=50)),
                ('video_url', models.URLField()),
                ('duration', models.IntegerField()),
                ('difficulty', models.CharField(choices=[('BEGINNER', 'Начинающий'), ('INTERMEDIATE', 'Средний'), ('ADVANCED', 'Продвинутый')], default='BEGINNER', max_length=12)),
                ('tags', models.CharField(max_length=200)),
                ('equipment_required', models.TextField(blank=True)),
                ('type', models.CharField(choices=[('KNOWLEDGE_BASE', 'База знаний'), ('FULL_TRAININGS', 'Полноценные тренировки')], default='FULL_TRAININGS', max_length=14)),
            ],
        ),
        migrations.CreateModel(
            name='TrainingSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('completed_at', models.DateTimeField(auto_now_add=True)),
                ('rating', models.PositiveIntegerField(null=True)),
            ],
        ),
    ]
